External Temperature Field
ilyasst/consolidation-works pull request #11
Opened 2020-09-08 21:53 UTC by arpcorrea

External Temperature Boundary Condition is now applied as a "Field object". Notice that if the problem shape is mxn, this field shpae is m+2xn+2

2020-09-18 16:44 UTC, ilyasst requested changes
Please consider the comments with the review. 

I believe that the function you wanted to demonstrate (the main point of the PR) is actually commented. Please double check that.

2020-09-18 16:44 UTC, ilyasst commented on consolidate/mesher/mesh.py
> +    def set_create_mask_edge(self, domain, totalNy, totalNx):
The `function set_create_mask_edge`is never used. It is commented in line 10 of this file. I could not find it being used elsewhere.

2020-09-18 16:44 UTC, ilyasst commented on consolidate/mesher/fields.py
> +            if field == "External Temperature":
We cannot have hard-coded values here. If we need to know which field is the external one, then the `Problem` class (in this case `TwoPlates`) should be the one to set the domain a certain attribute as `True` in `problem`.

2020-09-18 16:44 UTC, ilyasst commented on consolidate/problems/domains.py
> +        # import pdb; pdb.set_trace()
tiny pdb

2020-09-18 16:44 UTC, ilyasst commented on consolidate/problems/domains.py
> +        # import pdb; pdb.set_trace()
tiny pdb

2020-09-18 16:44 UTC, ilyasst commented on consolidate/problems/domains.py
> +            # import pdb; pdb.set_trace()
tiny pdb

2020-09-18 16:44 UTC, ilyasst commented on consolidate/problems/twoplates.py
> +        self.set_domains2(deck)
Not a good function name. Please change it.

2020-09-18 16:44 UTC, ilyasst commented on consolidate/mesher/fields.py
> +class Field:
The class `field` does not store the name of the field anywhere. It should have a `name` attribute, and maybe a `unit` attribute ?

2020-09-23 19:59 UTC, arpcorrea commented on consolidate/mesher/mesh.py
> +    def set_create_mask_edge(self, domain, totalNy, totalNx):
done

2020-09-23 19:59 UTC, arpcorrea commented on consolidate/problems/domains.py
> +        # import pdb; pdb.set_trace()
done

2020-09-23 19:59 UTC, arpcorrea commented on consolidate/problems/domains.py
> +        # import pdb; pdb.set_trace()
done

2020-09-23 19:59 UTC, arpcorrea commented on consolidate/problems/domains.py
> +            # import pdb; pdb.set_trace()
done

2020-09-23 20:00 UTC, arpcorrea commented on consolidate/problems/twoplates.py
> +        self.set_domains2(deck)
done

2020-09-23 20:26 UTC, arpcorrea commented on consolidate/mesher/fields.py
> +            if field == "External Temperature":
resolved. "problem" object has now an "external_boundary_fields" dictionary inside. This is read by mesh in order to create an "external mask"

2020-09-23 20:28 UTC, arpcorrea commented on consolidate/mesher/fields.py
> +class Field:
each Field object has a name (str) and a value (array). Do you think it is the case to modify?

2020-10-01 02:33 UTC, ilyasst approved these changes
Alright, it looks good to me :+1: 
I like the new changes in `RectangularDomain` but I think that part of those changes should be transferred to `problem`, otherwise it will be hard to get it to work with other problems.

2020-10-01 02:33 UTC, ilyasst commented on consolidate/problems/domains.py
>                      if self.position ==1:
This is a bit problematic. Defining the position of each domain with respect to another should be done in `problem` otherwise `RectangularDomain` will not work with all problems right ?

2020-10-01 02:33 UTC, ilyasst commented on consolidate/problems/domains.py
>                      if self.position ==1:
I like the new `RectangularDomain` class, but I think that in its current state it will not work for all problems.

2020-10-01 02:36 UTC, merged