Dev
ilyasst/consolidation-works pull request #14
Opened 2020-10-13 15:11 UTC by arpcorrea

Hello,
I would like to merge my dev code with your master. Here, as discussed, only TwoPlates.py is hard coded. RectangularDomain objects are now simpler, containing only masks, name, position (this last one I still need to work over it... couldn't find a solution yet) and local_fields. Mesher reads the local_fields of each RectangularDomain objects and sum them, creating Fields (like "global fields from locals").

2020-10-13 17:19 UTC, ilyasst requested changes
Please check my comments.

2020-10-13 17:20 UTC, arpcorrea commented on consolidate/problems/domains.py
>                          self.mask_external_boundary.update({"Bottom Edge": mask_bottom})
true... need to think about that...

2020-10-13 17:20 UTC, arpcorrea commented on consolidate/problems/domains.py
>                          self.mask_contact_interface.update({"Top Edge": contact_mask})
true... need to think about that...

2020-10-14 17:47 UTC, arpcorrea commented
Please have a look in the updates of this PR.

2020-11-09 18:21 UTC, ilyasst commented
Hey @arpcorrea what's up ? :)
Was wondering about this PR, should it still be open ? Where is the latest version right now ?
Should I review this one ?
Thanks

2020-11-09 18:22 UTC, arpcorrea commented
yes, it is still opened... it is the newest version (before overcoming the numerical issues)

2020-11-09 18:24 UTC, ilyasst commented
Should I review it ? If you have a latest version, could you update it please ?

Ilyass

On Nov 9 2020, at 1:22 pm, arpcorrea <notifications@github.com> wrote:
>
>
> yes, it is still opened... it is the newest version (before overcoming the numerical issues)
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub (https://github.com/ilyasst/consolidation-works/pull/14#issuecomment-724188935), or unsubscribe (https://github.com/notifications/unsubscribe-auth/AADMMM7ZLO2OO5GFOJFAYO3SPAXNTANCNFSM4SPCELKQ).
>

2020-11-09 18:30 UTC, arpcorrea commented
Yes please, go ahead with the review. I still do not have any further update yet (I am still looking around what to do to overcome the numerical issue - we talk about it on Wednesday). Remembering that this version can be ANY PLATE and it will automatically determine the borders (left, right - and top/bottom for the domains in the ends) and contacts (top and/or bottom for the inner domains). The unique condition for the code run properly is to define in the yaml file the domains as:
 "Something X", "Something X+1", ... "Something Xn". In practical example, it follows: "Plate 1", "Plate 2", "Plate 3" or "Domain 1", "Domain 2", "Domain 3" or even "Adherent 1", "Adherent 2", "Adherent 3".

2020-11-09 19:03 UTC, ilyasst requested changes

2020-11-09 19:03 UTC, ilyasst commented on consolidate/problems/twoplates.py
> +    def populate_fields_locally(self,deck):
I am currently thinking that this functions should not be part of of twoplates. 
Can the content of this function can be applied to any other domain ?

2020-11-24 14:08 UTC, arpcorrea commented on consolidate/models/heat_transfer.py
> +        self.dx = fields["dx"]
oh yeah... much smarter

2020-11-24 14:38 UTC, arpcorrea commented on consolidate/models/heat_transfer.py
> +        self.dx = fields["dx"]
actually it doesn't work... each field is an object, with name and value...

2020-11-24 19:55 UTC, ilyasst commented on consolidate/models/heat_transfer.py
> +        self.dx = fields["dx"]
You should still be able to do this, even if each field is an object. I probably got this wrong here `self.fields.dx`, but it should work.

2021-01-05 22:33 UTC, ilyasst requested changes
Please remove the comments and various pdbs (especially in the solver).
Also, is filename.csv necessary ?

I will merge after that.

2021-01-05 22:33 UTC, ilyasst commented on consolidate/solver/solves.py
>  class SolvesTwoPlates:
Cool name !

2021-01-06 13:45 UTC, arpcorrea commented on consolidate/problems/domains.py
>                          self.mask_external_boundary.update({"Bottom Edge": mask_bottom})
done, solve

2021-01-06 13:45 UTC, arpcorrea commented on consolidate/problems/domains.py
>                          self.mask_contact_interface.update({"Bottom Edge": contact_mask_middle_bottom})
done, solved

2021-01-06 13:47 UTC, arpcorrea commented on consolidate/mesher/mesh.py
> +# class Mesh:
new approach... local meshes are created in problem for later merge into a master mesh, done by the "Mesh" class

2021-01-12 04:06 UTC, merged